### ISSUE TITLE
Versioning is confusing

### ISSUE THREAD

**Issue by aleksei-korolev** [iota-wiki/iota-wiki#692]
While navigating through the wiki, it is not immediately obvious which version of the software I am reading about.

Version names do not match expections, as "Develop" doesn't mean anything to the end user. (is it IOTA network nightly build? is it the latest release of Shimmer?)

Not every page has versioning/matches versioning and versioning selection is not remembered.

When we combine all three, it means that users are never sure about which version of the network do they read right now.

**Comment by aleksei-korolev** [comment]
Related to #691

**Comment by muXxer** [comment]
IMO there should be 3 versions in the dropdown menu to provide docs for mainnet, shimmer, public testnet, because they can all be different.

IOTA is "production" branch in the repos. Currently it is the "Chrysalis" protocol version and it is live on "mainnet".
Develop is wrong completely... because develop doesn't fit the Shimmer network.
Develop fits the public testnet (which we call for comms reasons Shimmer Beta for now)
"Staging" branch in the repost would currently be equal to the "Stardust" protocol version and this will be the first version on "Shimmer network".

**Comment by Dr-Electron** [comment]
@muXxer Develop was just called "Develop" because Shimmer wasn't live yet and I couldn't come up with a better name 😓
Will close this issue as it is solved for now. Feel free to open another issue if you have more suggestions.
