### ISSUE TITLE
Next landing page/versioning proposal

### ISSUE THREAD

**Issue by aleksei-korolev** [iota-wiki/iota-wiki#693]
Taking into account #681 and #682,

1. Move technical topics: ISC, libraries, node software and developer resources to a separate page. Let's treat advanced users as developers from now on (for example, the guys who want to run IOTA/Shimmer nodes). This way we don't have to split, say, hornet documentation into "casual" and "for developers". It's all "technical". Pretty much the only exception is Firefly, we can live with that.
1. Put focus of the landing page on the very basic end user information and explaining the difference between IOTA and Shimmer.
1. Make version selection global.
1. Introduce a separate coloring scheme for Shimmer version ~~and play with fonts a bit :trollface:~~

**Comment by huhn511** [comment]
> Introduce a separate coloring scheme for Shimmer version
This is an awesome idea!

**Comment by jlvandenhout** [comment]
3. Requires all projects to adopt the same versioning strategy. I agree this would be ideal, but might not be possible as some projects are network agnostic and use semantic versioning for example. We might store a global preferred version though which we look at first when navigating to a project, and if the it doesn't have that version, we use its own versioning.

**Comment by aleksei-korolev** [comment]
@jlvandenhout what if we point both IOTA and Shimmer docs to the same branch?

Also I think it might make sense to abstract IOTA/Shimmer version toggle from the package versioning. So we would have a global toggle for networks, but devs would still be free to publish docs for multiple different versions (LTE, Stable, Nightly or the like).

**Comment by jlvandenhout** [comment]
I see what you mean. That would work for both the introductory content as well as the project-specific content. Although it would be impossible for us as Wiki maintainers to track what versions would work in what ecosystems, so that specification should be done on the project side by maintainers. Then the process would be:

1. Project maintainers create different versions of their project, whatever their versioning scheme might be, as long as they create a branch per version.
2. Project maintainers tag their versions with the ecosystems they are compatible with (note this is an N to N relationship: a single version could be compatible with multiple ecosystems and multiple versions can be compatible with a single ecosystem)
3. Wiki maintainers pull the branches of the versions we want to include in the Wiki.
4. The Wiki has a global switcher between ecosystems and for each ecosystem we list the compatible project versions.

I really like this idea actually.

**Comment by jlvandenhout** [comment]
@Dr-Electron wdyt of the above?

**Comment by Dr-Electron** [comment]
> > Introduce a separate coloring scheme for Shimmer version
> 
> this is an awesome idea!

Initially it was from @JSto91 I think. We moved away from it as we weren't sure if it would be too much tho 🤔

**Comment by Dr-Electron** [comment]
> @Dr-Electron wdyt of the above?

I thought that was one of the initial ideas. At least it is similar.
Let's use for example identity, as they are (as of now) network agnostic
They would have:
0.8.0-shimmer
0.7.0-shimmer
0.6.0
0.5.0

So if the user has selected `Shimmer` he would be redirected to 0.8.0. 
If he selects `IOTA` he would be redirected to 0.6.0

Keep in mind: Do we now need a `stable` version for all networks? How do we handle testnet? As it won't need that feature 🤔

**Comment by Dr-Electron** [comment]
I think we can close this one? I mean our landing page(s) are still a mix of Developer and User content but I think with the current Navbar that should be fine 🤔
