### ISSUE TITLE
Search results are broken

### ISSUE THREAD

**Issue by Thoralf-M** [iota-wiki/iota-wiki#794]
**Describe the bug**
The search results are broken https://wiki.iota.org/search?q=native%20token
All links there return `Page Not Found`

**To Reproduce**

1. Go to https://wiki.iota.org/search?q=native%20token
2. Click on a link
3. See error

**Expected behavior**
Results should go to a working page

**Desktop (please complete the following information):**

- OS: [pop!_os]
- Browser [ chrome]

**Comment by jlvandenhout** [comment]
Looks like this is still an issue and something going wrong with the paths. All of them have a slash at the end, if I remove that the link works 🤔 @begonaalvarezd might be the `trailingSlash: true` setting in combination with Vercel? This might help: https://github.com/slorber/trailing-slash-guide

**Comment by begonaalvarezd** [comment]
> Looks like this is still an issue and something going wrong with the paths. All of them have a slash at the end, if I remove that the link works thinking @begonaalvarezd might be the `trailingSlash: true` setting in combination with Vercel? This might help: https://github.com/slorber/trailing-slash-guide

I think the issue is not realted to the `trailingSlash: true`, if you modify the DOM and navigate to the URL without the trailing slash it also returns a 404. The issue afaik is the same as before, and its because its linking to a URL outside of currently selected network, which tries to route it as a SPA but the route doesnt exist because it belongs to a different docusaurus. The problem is solved if you refresh the page, which gives a hint that the search results should refresh the page instead of using a normal SPA routing link, when they link to a different network (differerent docusaurus).

**Comment by jlvandenhout** [comment]
The search results are filtered per environment, so results are within the current environment only. But yeah looks like the search result page is outside client-side routing.
